package com.pyg.mapper;

import com.pyg.pojo.TbAreas;
import com.pyg.pojo.TbAreasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    long countByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int deleteByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insert(TbAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insertSelective(TbAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    List<TbAreas> selectByExample(TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbAreas record, @Param("example") TbAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExample(@Param("record") TbAreas record, @Param("example") TbAreasExample example);
}