package com.pyg.mapper;

import com.pyg.pojo.TbGoodsDesc;
import com.pyg.pojo.TbGoodsDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGoodsDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    long countByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int deleteByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insert(TbGoodsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insertSelective(TbGoodsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    List<TbGoodsDesc> selectByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbGoodsDesc record, @Param("example") TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_desc
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExample(@Param("record") TbGoodsDesc record, @Param("example") TbGoodsDescExample example);
}