package com.pyg.mapper;

import com.pyg.pojo.TbPayLog;
import com.pyg.pojo.TbPayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    long countByExample(TbPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int deleteByExample(TbPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insert(TbPayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int insertSelective(TbPayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    List<TbPayLog> selectByExample(TbPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbPayLog record, @Param("example") TbPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    int updateByExample(@Param("record") TbPayLog record, @Param("example") TbPayLogExample example);
}