package com.pyg.pojo;

import java.io.Serializable;
import java.util.List;

public class TbSpecification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification.id
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification.spec_name
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    private String specName;

    private List<TbSpecificationOption> specOptionList;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_specification
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification.id
     *
     * @return the value of tb_specification.id
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification.id
     *
     * @param id the value for tb_specification.id
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification.spec_name
     *
     * @return the value of tb_specification.spec_name
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification.spec_name
     *
     * @param specName the value for tb_specification.spec_name
     *
     * @mbg.generated Wed Sep 19 15:49:32 CST 2018
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    public List<TbSpecificationOption> getSpecOptionList() {
        return specOptionList;
    }

    public void setSpecOptionList(List<TbSpecificationOption> specOptionList) {
        this.specOptionList = specOptionList;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("TbSpecification{");
        sb.append("id=").append(id);
        sb.append(", specName='").append(specName).append('\'');
        sb.append(", specOptionList=").append(specOptionList);
        sb.append('}');
        return sb.toString();
    }
}